import React, { useState } from 'react';
import styles from './brands-block.module.scss';
import { BlockLayout } from '../../components/block-layout/block-layout';
import { Button } from '../../components/button/button';
import { brandsImages } from '../../autogenerated/brands-images';

export const BrandsBlock = () => {
    const [showMore, setShowMore] = useState(false);
    const brands = showMore ? brandsImages : brandsImages.slice(0, 20);
    return (
        <BlockLayout
            title="Ремонтируем все бренды холодильников"
            description="ПрофХолод предоставляет гарантийный ремонт и сервисное обслуживание холодильников данных брендов.
            Мы заслужили доверие благодаря долгому сотрудничеству и стабильно высокому качеству работы."
            id="brands"
            paddingBottom
            paddingTop
        >
            <div className={styles.list}>
                {brands.map((image, i) => {
                    return (
                        <div key={i} className={styles.item}>
                            <div className={styles.imageWrap}>
                                <img src={image} alt="" loading="lazy" />
                            </div>
                        </div>
                    );
                })}
            </div>
            <div className={styles.button}>
                <Button onClick={() => setShowMore(!showMore)} fullWidth>
                    {showMore ? 'Скрыть бренды' : 'Показать все бренды'}
                </Button>
            </div>
        </BlockLayout>
    );
};
