import React from 'react';
import styles from './certificates-block.module.scss';
import { BlockLayout } from '../../components/block-layout/block-layout';
import { certificatesImages } from '../../autogenerated/certificates-images';
import { Slider } from '../../components/slider/slider';

export const CertificatesBlock = () => {
    return (
        <BlockLayout title="Сертификаты и партнеры" id="certificates" paddingBottom>
            <Slider
                slides={certificatesImages.map((item, i) => {
                    return (
                        <div className={styles.imageWrap} key={i}>
                            <img src={item} alt="" loading="lazy" />
                        </div>
                    );
                })}
                classNames={{ swiper: styles.swiper, navigation: styles.navigation }}
            />
        </BlockLayout>
    );
};
