import fs from 'fs';
/** Перед использование установить в package.json 
  "type": "module",*/
main();
function main() {
    const certificatesImagesPath = './src/assets/images/certificates';
    const outFile = './src/autogenerated/certificates-images.ts';

    const certificatesImages = fs.readdirSync(certificatesImagesPath);
    const resultImports = [];
    const resultImageNames = [];

    for (let i = 0; i < certificatesImages.length; i++) {
        const image = certificatesImages[i];
        const imageName = `image${i}`;
        resultImports.push(`import ${imageName} from '../assets/images/certificates/${image}';`);
        resultImageNames.push(`${imageName}`);
    }

    const result =
        resultImports.join('\n') + `\n\nexport const certificatesImages = [${resultImageNames.join(',\n')}];`;

    fs.writeFileSync(outFile, result);
}
