import fs from 'fs';

main();
function main() {
    const brandsImagesPath = './src/assets/images/brands';
    const outFile = './src/autogenerated/brands-images.ts';

    const brandsImages = fs.readdirSync(brandsImagesPath);
    const resultImports = [];
    const resultImageNames = [];

    for (let i = 0; i < brandsImages.length; i++) {
        const image = brandsImages[i];
        const imageName = `image${i}`;
        resultImports.push(`import ${imageName} from '../assets/images/brands/${image}';`);
        resultImageNames.push(`${imageName}`);
    }

    const result = resultImports.join('\n') + `\n\nexport const brandsImages = [${resultImageNames.join(',\n')}];`;

    fs.writeFileSync(outFile, result);
}
